/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.ArrayDeNumeros;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class App extends javax.swing.JFrame {

    private ArrayDeNumeros colecao;

    public App() {
        initComponents();
        colecao = new ArrayDeNumeros();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPVetores = new javax.swing.JPanel();
        jLNumeros = new javax.swing.JLabel();
        jTFNumeros = new javax.swing.JTextField();
        jPResultado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAResultado = new javax.swing.JTextArea();
        jPOperaçoes = new javax.swing.JPanel();
        jBAdicionar = new javax.swing.JButton();
        jBPreenche = new javax.swing.JButton();
        jBSoma = new javax.swing.JButton();
        jBInverter = new javax.swing.JButton();
        jBOrdenar = new javax.swing.JButton();
        jBHistograma = new javax.swing.JButton();
        jBDivisivel = new javax.swing.JButton();
        jBPar = new javax.swing.JButton();
        jBSubstitui = new javax.swing.JButton();
        jBBuscaBinaria = new javax.swing.JButton();
        jBRetornaIndice = new javax.swing.JButton();
        jBRepetente = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPVetores.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores"));

        jLNumeros.setText("Numeros:");

        jTFNumeros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFNumerosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFNumerosFocusLost(evt);
            }
        });
        jTFNumeros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNumerosKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPVetoresLayout = new javax.swing.GroupLayout(jPVetores);
        jPVetores.setLayout(jPVetoresLayout);
        jPVetoresLayout.setHorizontalGroup(
            jPVetoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVetoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNumeros)
                .addGap(18, 18, 18)
                .addComponent(jTFNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPVetoresLayout.setVerticalGroup(
            jPVetoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVetoresLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPVetoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumeros)
                    .addComponent(jTFNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        jTAResultado.setColumns(20);
        jTAResultado.setRows(5);
        jScrollPane1.setViewportView(jTAResultado);

        javax.swing.GroupLayout jPResultadoLayout = new javax.swing.GroupLayout(jPResultado);
        jPResultado.setLayout(jPResultadoLayout);
        jPResultadoLayout.setHorizontalGroup(
            jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadoLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPResultadoLayout.setVerticalGroup(
            jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );

        jPOperaçoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações"));

        jBAdicionar.setText("Adicionar");
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jBPreenche.setText("Preencher coleção");
        jBPreenche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPreencheActionPerformed(evt);
            }
        });

        jBSoma.setText("Somar");
        jBSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSomaActionPerformed(evt);
            }
        });

        jBInverter.setText("Inverter valores");
        jBInverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInverterActionPerformed(evt);
            }
        });

        jBOrdenar.setText("Ordenar coleção");
        jBOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOrdenarActionPerformed(evt);
            }
        });

        jBHistograma.setText("Histograma");
        jBHistograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHistogramaActionPerformed(evt);
            }
        });

        jBDivisivel.setText("Valor divisível");
        jBDivisivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDivisivelActionPerformed(evt);
            }
        });

        jBPar.setText("Números Pares");
        jBPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBParActionPerformed(evt);
            }
        });

        jBSubstitui.setText("Substituir valor");
        jBSubstitui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSubstituiActionPerformed(evt);
            }
        });

        jBBuscaBinaria.setText("Busca binária");
        jBBuscaBinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscaBinariaActionPerformed(evt);
            }
        });

        jBRetornaIndice.setText("Retornar índice");
        jBRetornaIndice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRetornaIndiceActionPerformed(evt);
            }
        });

        jBRepetente.setText("Valor Repetente");
        jBRepetente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRepetenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOperaçoesLayout = new javax.swing.GroupLayout(jPOperaçoes);
        jPOperaçoes.setLayout(jPOperaçoesLayout);
        jPOperaçoesLayout.setHorizontalGroup(
            jPOperaçoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOperaçoesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPOperaçoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBInverter)
                    .addComponent(jBSoma)
                    .addComponent(jBPreenche)
                    .addComponent(jBAdicionar)
                    .addComponent(jBOrdenar)
                    .addComponent(jBHistograma)
                    .addComponent(jBDivisivel)
                    .addComponent(jBPar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPOperaçoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPOperaçoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSubstitui, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBBuscaBinaria, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBRetornaIndice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBRepetente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPOperaçoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBAdicionar, jBBuscaBinaria, jBDivisivel, jBHistograma, jBInverter, jBOrdenar, jBPar, jBPreenche, jBRetornaIndice, jBSoma, jBSubstitui});

        jPOperaçoesLayout.setVerticalGroup(
            jPOperaçoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOperaçoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBPreenche)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBSoma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBInverter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBOrdenar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSubstitui)
                .addGap(11, 11, 11)
                .addComponent(jBHistograma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDivisivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBPar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBBuscaBinaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBRetornaIndice)
                .addGap(7, 7, 7)
                .addComponent(jBRepetente))
        );

        jPOperaçoesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBAdicionar, jBBuscaBinaria, jBDivisivel, jBHistograma, jBInverter, jBOrdenar, jBPar, jBPreenche, jBRetornaIndice, jBSoma, jBSubstitui});

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPVetores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPOperaçoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBSair)
                        .addGap(88, 88, 88))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jPResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPVetores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPOperaçoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBSair)
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
        if (jTFNumeros.getText().isEmpty()) {
            JOptionPane.showInputDialog(this, "Informe o número a ser adicionado", "Aviso", 0);
            jTFNumeros.requestFocusInWindow();
            jTFNumeros.setText(null);
            return;
        }

        if (!colecao.adiciona(Integer.parseInt(jTFNumeros.getText()))) {
            JOptionPane.showMessageDialog(this, "Não foi possível adicionar. Coleção Completa", "Aviso", 0);
            return;
        }

        jTAResultado.setText(colecao.dados());
        jTFNumeros.setText(null);
        jTFNumeros.requestFocusInWindow();
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jBPreencheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPreencheActionPerformed
        colecao.preenche();
        jTAResultado.setText(colecao.dados());
    }//GEN-LAST:event_jBPreencheActionPerformed

    private void jTFNumerosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNumerosFocusGained
        if (evt.getSource() instanceof javax.swing.JTextField) {
            javax.swing.JTextField campo = (javax.swing.JTextField) evt.getSource();
            campo.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_jTFNumerosFocusGained

    private void jTFNumerosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNumerosFocusLost
        if (evt.getSource() instanceof javax.swing.JTextField) {
            javax.swing.JTextField campo = (javax.swing.JTextField) evt.getSource();
            campo.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jTFNumerosFocusLost

    private void jTFNumerosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNumerosKeyTyped
        char tecla = evt.getKeyChar();
        if (!Character.isDigit(tecla) && tecla != '.') {
            this.getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTFNumerosKeyTyped

    private void jBSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSomaActionPerformed
        colecao.soma();
        jTAResultado.setText(colecao.dados() + "\n A soma de todos os valores é: " + colecao.soma());

    }//GEN-LAST:event_jBSomaActionPerformed

    private void jBOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOrdenarActionPerformed
        colecao.ordenar();
        jTAResultado.setText(colecao.dados());
    }//GEN-LAST:event_jBOrdenarActionPerformed

    private void jBHistogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHistogramaActionPerformed
        colecao.histograma();
        jTAResultado.setText(colecao.dados() + "\n Histograma: " + colecao.histograma());
    }//GEN-LAST:event_jBHistogramaActionPerformed

    private void jBDivisivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDivisivelActionPerformed
        int divisor = Integer.parseInt(JOptionPane.showInputDialog(this, "Qual número deseja buscar a posição?", "App", 3));
        int divide[] = colecao.dividir(divisor);
        if (divide != null) {
            jTAResultado.setText(colecao.dados() + colecao.divididosToString(divide, "\nOs números divisíveis por: " + divisor + " são: "));
        } else {
            jTAResultado.setText("Não existe números divisíveis por: " + divisor);
        }


    }//GEN-LAST:event_jBDivisivelActionPerformed

    private void jBParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBParActionPerformed

        int par[] = colecao.par();
        if (par != null) {
            jTAResultado.setText(colecao.dados() + colecao.divididosToString(par, "\nOs números pares são: "));
        } else {
            jTAResultado.setText("Não existe números pares nessa coleção!");
        }
    }//GEN-LAST:event_jBParActionPerformed

    private void jBSubstituiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSubstituiActionPerformed
        int localiza = Integer.parseInt(JOptionPane.showInputDialog(this, "Informe o número que deseja substituir?", "App", 0));
        colecao.substitui(localiza);

        if (colecao.substitui(localiza) == false) {
            JOptionPane.showMessageDialog(this, "Nenhum valor encontrado", "Aviso", 0);
        } else {
            int substituto = Integer.parseInt(JOptionPane.showInputDialog(this, "Informe o novo número?", "App", 0));
            colecao.substituir(localiza, substituto);

            jTAResultado.setText(colecao.dados());
        }
    }//GEN-LAST:event_jBSubstituiActionPerformed

    private void jBBuscaBinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscaBinariaActionPerformed
        int x = Integer.parseInt(JOptionPane.showInputDialog(this, "Qual número deseja buscar?", "App", 3));
        colecao.buscaBinaria(x);
        if (colecao.buscaBinaria(x) != -1) {
            jTAResultado.setText(colecao.dados() + "\n O número: " + x + " foi encontrado");

        } else {
            JOptionPane.showMessageDialog(this, "Não encontramos o número : " + x, "", 1);
        }

    }//GEN-LAST:event_jBBuscaBinariaActionPerformed

    private void jBInverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInverterActionPerformed
        colecao.inverte();
        jTAResultado.setText(colecao.dados());
    }//GEN-LAST:event_jBInverterActionPerformed

    private void jBRetornaIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRetornaIndiceActionPerformed
        int acha = Integer.parseInt(JOptionPane.showInputDialog(this, "Qual número deseja buscar a posição?", "App", 3));
        int posicoes[] = colecao.posicao(acha);
        if (posicoes != null) {
            jTAResultado.setText(colecao.vetorToString(posicoes, "O valor " + acha + " foi localizado em: "));
        } else {
            jTAResultado.setText("O valor " + acha + " não foi localizado na coleção! ");
        }


    }//GEN-LAST:event_jBRetornaIndiceActionPerformed

    private void jBRepetenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRepetenteActionPerformed
        colecao.valorRepetente();
        jTAResultado.setText(colecao.dados() + "\n" + colecao.valorRepete());
    }//GEN-LAST:event_jBRepetenteActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBBuscaBinaria;
    private javax.swing.JButton jBDivisivel;
    private javax.swing.JButton jBHistograma;
    private javax.swing.JButton jBInverter;
    private javax.swing.JButton jBOrdenar;
    private javax.swing.JButton jBPar;
    private javax.swing.JButton jBPreenche;
    private javax.swing.JButton jBRepetente;
    private javax.swing.JButton jBRetornaIndice;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBSoma;
    private javax.swing.JButton jBSubstitui;
    private javax.swing.JLabel jLNumeros;
    private javax.swing.JPanel jPOperaçoes;
    private javax.swing.JPanel jPResultado;
    private javax.swing.JPanel jPVetores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAResultado;
    private javax.swing.JTextField jTFNumeros;
    // End of variables declaration//GEN-END:variables
}
